### ISSUE TITLE
commands

### ISSUE THREAD

**Issue by pranavbhuv** [CzechPMDevs/WorldFixer#5]
no commands work alpha 8
6.10 01:11:06 [Server] Server thread/DEBUG Still 3 bytes unread in CommandRequestPacket: 0x000000
26.10 01:11:14 [Server] Server thread/DEBUG Still 3 bytes unread in CommandRequestPacket: 0x000000
26.10 01:11:16 [Server] Server thread/DEBUG Still 3 bytes unread in CommandRequestPacket: 0x000000

**Comment by GamakCZ** [comment]
New version is for api 3.0.0-ALPHA9, try download older version.

**Comment by pranavbhuv** [comment]
Do you have a, phar I can use idm which version.

**Comment by pranavbhuv** [comment]
for pmmp

**Comment by GamakCZ** [comment]
probably was the bug elsewhere, try using the version 35 (https://poggit.pmmp.io/babs/7630)

**Comment by pranavbhuv** [comment]
Im using latest build from jenkins. Commands work. Says world hs been fixed. But it hasnt still see rails see this error tho..
10 14:04:15 [Server] INFO int(0)
26.10 14:04:15 [Server] INFO }
26.10 14:04:15 [Server] INFO [144]=>
26.10 14:04:15 [Server] INFO array(2) {
26.10 14:04:15 [Server] INFO [0]=>

**Comment by GamakCZ** [comment]
it is fixed.
